name: GitHub-Profile-3D-Contrib

on:
  schedule: #  Runs at 06:00 UTC, which corresponds to 00:00 CST
    - cron: "0 6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v3
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
      - name: Commit & Push
        run: |
          git config user.name Pikago-hub
          git config user.email wuxiaozhu9821@hotmail.com
          git add -A .
          git commit -m "generated"
          git push
